### ISSUE TITLE
provide enc(ppid) in user data

### ISSUE THREAD

**Issue by amiller** [Dstack-TEE/dstack#20]
The DCAP Quoting Public Library follows a convention of putting a cpu-specific idenfitier `Encrypted(PPID)` into the `user_data` field of the header.

A sample user data looks like this: 
`83fbfe61525f55581315cd9dc950f44700000000`

Notes from the docs: https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_TDX_DCAP_Quoting_Library_API.pdf
> User Data 20 Byte Array Custom user-defined data. For the Intel® SGX and
> TDX DCAP Quote Generation Libraries, the first 16
> bytes contain a Platform Identifier that is used to
> link a PCK Certificate to an Enc(PPID). This
> identifier is consistent for every quote generated
> with this QE on this platform.

Here's where it's copied into `header.user_data` in the qpl.
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/main/QuoteGeneration/quote_wrapper/quote/enclave/quoting_enclave_3.cpp#L1604

I notice that the quotes provided by Dstack right now do not include this. 
The quotes produced by dstack seem to have just 5 bytes set, like this: `b4818442ef700000000000000000000000000000`

I think it is because the `tdx-attest-sys` is too low level, and so dstack is bypassing the quoting library that provides this functionality.

This is important because I'd really like to be able to use Enc(PPID) as a way of providing sealing keys from SGX to TDX.

**Comment by kvinwang** [comment]
> I think it is because the `tdx-attest-sys` is too low level, and so dstack is bypassing the quoting library that provides this functionality.

Thanks for the report.

The quote is actually generated by QE which is a sgx enclave compiled from the source code you linked here and signed by Intel.
The `tdx-attest-sys` is just a client talking to the QE via VSOCK, as show below:
```
App -> tdx-attest-sys ----------------> QGS -> QE
^^^^^^^^^^^^^^^^^^^^^   ^^^^^^^^^^^^    ^^^^^^^^^
      TD guest             VSOCK         TDX host
```
I'll investigate in detail later.

**Comment by amiller** [comment]
thanks kevin you're right after trying to reproduce this on a fresh node, the user data is exactly what i expected. I think my report here was based on an old quote. Sorry for the trouble!
